footprint: [[-0.76, -0.69], [-0.76, 0.69], [0.76, 0.69], [0.76, -0.69]]
footprint_padding: 0.1

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.1

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: point_cloud_sensor #laser_scan_sensor
    point_cloud_sensor: {data_type: PointCloud2, clearing: true, marking: true, topic: velodyne_points, inf_is_valid: true}
    #laser_scan_sensor: {data_type: LaserScan, clearing: true, marking: true, topic: laser/scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.6
