obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.76, -0.69], [-0.76, 0.69], [0.76, -0.69], [0.76, 0.69]]
#robot_radius: ir_of_robot
inflation_radius: 1.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: velodyne, data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true}
